git:
  depth: 1
cache:
  yarn: true
  directories:
  - node_modules
matrix:
  fast_finish: true
language: node_js
node_js:
- '7'
dist: trusty
notifications:
  slack: binary-group:xEVrYY0QGz7fbwJqi4LMWbBS
  email:
  - arnab@binary.com
  - apoorv@binary.com
branches:
  only:
  - master
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- yarn
install:
- yarn test
env:
  global:
    secure: cpcTv4KqDc6XgiGyraLpAI0fGbOZ9krDeOiwLnPBa+8KAZHRByMm9nKDzMUE5PJPAZfpb/xRFLFC/yP3skWYMH/XPMXsBm/4RqzDwEKLB6WDlhn0j4XSsS51qpIc8L2XZfoM8EhMGLn5UUt1F8i5j+oEHlKdJ1kBHRTo2WdArN6RrMTWN2s7+6mcS55Ec3dAsIR8WZtmxio5axocBLJ3wqrOOfBcmdW/DmGMcZsrIFtPS9LA8ksgiIFzAinODhXGEixsfUB3bi31w556ylXQaW0wrSIfsPQajC/ysrZNUc1EJx3mLpNyLHexE0+heq69QhuonXgP1RRRHs+QelHr5y6p4KfAMeUyfQNRwbyj8iZg6Stkjcjf8or6zg9TZCanZGvhNg5PiY0MTGELCNE/ojuoOF4l+hrj0usPO02SwlE07JgX6Kudb+WqaYdDrg7A2LB3HRXzsXtc8miv8H5SPobcjad9X8Kvkpw4nea6SiVozFQkvTALbeNNGY15eGRVeUc0L+X9xmoNtvQ+02I21PDJfW7ed3duYawQBFNQW29FRN1VujLHhcZLDgQ3MRVNnOf2pE30QJsJRk7I9O+/XGz/Csz1nIS1eah5wLpYpKC3z4oHN5kJQVIUKCx0oo/cq4fJ++9zQggfwxZNvrQtuPmvWmtKDH65xEzAm2R+EwI=
