git:
  depth: 1
cache:
  yarn: true
  directories:
  - node_modules
matrix:
  fast_finish: true
language: node_js
node_js:
- '7'
dist: trusty
addons:
  chrome: stable
notifications:
  slack: binary-group:xEVrYY0QGz7fbwJqi4LMWbBS
  email:
  - arnab@binary.com
  - apoorv@binary.com
branches:
  only:
  - master
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- yarn
install:
- yarn test
env:
  global:
  - secure: XMTUIOONfdnIlGS0YxIvPyRYZTLREBGUr5XEC0q8smMBJbJGUPZVMxd47tUPjTd9gwCPHTtjxVT+AFBKRxUmt10Mdqov/Ye0WxLA/CNSCmZ/HCc8U3vFckH9HCSSq7/KqMHlfXG5URicIBR4h0caaIdDAV2q40Z7A1svvR+LIRjAuRvOEa/dmeZBGC2Pl+sI2fWKt0AJz5FKge11OPW+B0RUjfdqQcTPjHlB3MQiO1XK3twyei4F5q6z/agK23WuLW/lTFjoA/OpH8lyJ6JkD0KZO2gWL9EVqlZqcPf5d1ekZOMUB4a6GZ02uvqTPZZpL4Rl7kyxKUxrQkL8K2lItZsZUPkC/VIqo6l0IhJSEFYJpTeUkenzoVMhcJAwIaKdtKUaAnJ+YXyD9+yBbD8qHCDTkoHEP9JlCx1w89Se8BmH06U4wTwYDAkhk6SvHzkc11XWw65kZi02vkZ+5wiVgJKNIzwya+MPb9Kwdwak91NEch2MpsBhvcwugwUIPTy0VLB2C9fiQ8Nz9LUvkmp/86i+ykqpUrdetETVKimQRIjCVREt7sVMq28agGNbUQe0r04oEfB23P3E/vKSz9lIXNKzaXQ0Xi9LjCFWjGfK4y6K3DxVVIjy0+HCa6LyEEilq6bj2wKQAVrAFejqYCy3322RclTlfmo6SPbPh3cJ8+Y=
  - secure: Mh60Sqj7zF4+t+pvVp1TGW88HKWD48IimvE5dbIDjVFAds54ep1rZ7jGqKkEypk1ama9xUzAy63mCJX064vngB/4W7bnTFQxKwKaHmWufcvFWizJh9nz2Aoyz4X4opkkY1Hn1xYdD8qSNYwMMdRsGVA0ylpGwsf7EE0bdGup11y/m0Wry1Q5NMv4daH8e5qqYIJJUFVYvnlIuRH/s8qnIBHlQMpQ2+lb5oMsuLvRvIqiZmDqnpwslW+3FhtFdoYMI3ui4IAeOzEWeOVLfFozreEO8eyP1ybthv313dNkH8Z1KRrxcJZgGTYQ3eClIEGb1zCebg6HYIgSp2lzVbkcP+SMLWPEiHLhUsc2x779IMAb5nv5wxmMjY14lEGPy24t6bDcNu+pax3IcCUKS4gvmsO2s9j4lOCWb9IYQdAcHGj+siAt8he8Eek418Orrl3qslVjzw1EsmqttVpmYAJbhEKO7k77v/oF+v6I9/hbE+2LuHLUUzamcR6CxcjcNNfuSPhCdclUb4MgcuZ3a+lsSO5Ijn1uApcVADrWhSPRBotJfjzAUMWViFw20UraSkc5yrZtPufdnn+usA7zawNIRZN0H/68uWhSMwRiiAzxBfzdRKVP3DywHr9KvGT2YuPP5hHquBJcwzmGjQ/rrOVl77FxACg7kTVG9g8fSjh7hLo=
